Configure prettier
meilisearch/docs-searchbar.js pull request #354
Opened 2021-06-08 07:18 UTC by mdubus

## What's wrong ?
Prettier was installed but the rules weren't configured properly. There was different coding styles in different files. Lack of uniformity. 

## What's inside this PR ?
Edit of the configuration file, and formatting of every file regarding the same specification.
Please take a look at the rules to see if it seems coherent to you 🙏

2021-06-08 13:00 UTC, bidoubiwa commented
bors try

2021-06-08 13:05 UTC, bidoubiwa requested changes
In the contributing.md there is still the following: 

```
# Linter with auto-correct
yarn lint-fix
# Prettier for Markdown (auto-correct)
yarn format:md
# Prettier for SCSS (auto-correct)
yarn format:scss
```

Could you change the `lint-fix` and also test the format to see if they work properly?

2021-06-08 13:05 UTC, bidoubiwa commented on .prettierignore
> +**/dist/
```suggestion
**/dist/

```

2021-06-08 13:11 UTC, bidoubiwa commented
Also in the contributing.md apparently the linter recognizes that the code is `.js` thus he does not lint what is not `.js`. 

So you have the following at the bottom of the file: 

```
"version": "X.X.X",

export default 'X.X.X'
```

Could you replace the double quotes with simple quotes?

2021-06-08 13:18 UTC, mdubus commented
> In the contributing.md there is still the following:
> 
> ```
> # Linter with auto-correct
> yarn lint-fix
> # Prettier for Markdown (auto-correct)
> yarn format:md
> # Prettier for SCSS (auto-correct)
> yarn format:scss
> ```
> 
> Could you change the `lint-fix` and also test the format to see if they work properly?

Nice catch ! I tested them and they work perfectly 👌

2021-06-09 09:09 UTC, bidoubiwa approved these changes
bors merge

2021-06-09 09:11 UTC, merged